name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql root password: 12345678
        mysql database: sportnite
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Update database
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        dotnet ef database update --project SportNiteServer

#    - name: Execute unit tests
#      run: dotnet test -l:trx /p:CollectCoverage=true /p:CoverletOutput=Coverage/ /p:CoverletOutputFormat=lcov
      
#    - name: Publish Test Results
#      uses: EnricoMi/publish-unit-test-result-action@v2
#      with:
#        trx_files: "SportNiteServer.Tests/TestResults/**/*.trx"

#    - name: Coveralls
#      uses: coverallsapp/github-action@master
#      with:
#        github-token: ${{ secrets.GITHUB_TOKEN }}
#        path-to-lcov: SportNiteServer.Tests/Coverage/coverage.info